WIP Create a CFH message
CraftAcademy/building_blocks_mobile pull request #3
Opened 2017-04-19 13:04 UTC by casperjureskog

**PT Story:**   https://www.pivotaltracker.com/story/show/143863477

2017-04-20 09:14 UTC, tochman commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
So what's happening after the message is sent?

2017-04-20 09:20 UTC, diraulo requested changes
Try to stay consistent in your naming :)
Also when working on UI/Client stuff, always attach a screenshot of your changes to the PR description

2017-04-20 09:20 UTC, diraulo commented on www/js/app.js
> +    url: '/message',
why aren't you using `help_request`, IMO it's good to keep some consistency on how you name your resources and associated routes. It helps when reading the code, I can immediately tell what's what.

2017-04-20 09:20 UTC, diraulo commented on www/js/app.js
> +        templateUrl: 'templates/message/message.html',
same here with your views.

2017-04-20 09:20 UTC, diraulo commented on www/js/controllers.js
> +.controller('MessageController', function($scope, HelpRequest) {
Same here, how about `HelpRequestController`?

2017-04-20 14:35 UTC, Scharrre97 commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
you will get a thank you message, I just updated the screenshot... have a look @tochman

2017-04-20 14:47 UTC, tochman commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
That's it? No redirect to another page?

2017-04-20 14:49 UTC, Scharrre97 commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
Well.. not at this moment. Stay agile.

2017-04-20 14:49 UTC, tochman commented on www/js/controllers.js
> +      // This error handler needs to be refactored before PR. This is cruede
Please note this comment. Act on it or delete it ;-)

2017-04-20 14:50 UTC, Scharrre97 commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
I think that's out of scope for this feature.. we can add a new feature to our PT for that.

2017-04-20 14:50 UTC, Scharrre97 commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
Or what do you think? @tochman

2017-04-20 14:51 UTC, tochman commented on www/js/controllers.js
> +      // Move on to another page or whatever you want to do
Agile does not mean bad UX

2017-04-20 15:08 UTC, tochman approved these changes
Okay.

2017-04-20 15:11 UTC, Scharrre97 commented on www/js/controllers.js
> +      // This error handler needs to be refactored before PR. This is cruede
yes, totally right there. on our way to fix it :)

2017-04-21 07:05 UTC, tochman commented
Can you take a look again @diraulo ?

2017-04-21 09:13 UTC, diraulo approved these changes

2017-04-21 09:13 UTC, merged